source 'git@github.com:CocoaPods/Specs.git'
platform :ios, '9.0'

target 'SSRWeexDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSRWeexDemo
  pod 'WeexSDK', '~> 0.24.0'

end
